OWASP/german-owasp-day

- archive/2017/talk/08-talk.html
Abstract for the Script Gadget talk
> + Abstract for Script Gadget talk

- about/index.html
- archive/2017/talk/07-lightning-talk-03.html
- location/evening/index.html
- schedule/index.html
- sponsors/index.html
We got a new lightning talk :-)
> + TLS-Attacker 2.0 as lightning talk

- index.html
> 2019 updates

- contact/index.html
- index.html
The mail address was pointing to the old mailman.
Also replaced 2018 with 2019 in the metadata
> 2018->2019 in metadata and fix email address

- cfp/index.html
- contact/index.html
- index.html
- location/conference/index.html
- location/evening/index.html
CFP was announced by Martin via the mailing list today.
Updated the website with event locations and cfp, so we can share it on social media, etc.
> added cfp and event locations

- about/index.html
- cfp/index.html
- location/conference/index.html
> Fixing headers and a stray <b>

- index.html
Irgendwie hatte ich den ganzen Satz mal irgendwo schöner gemacht. War das hier?
> DV ist so ziemlich angestaubt ;-)

- 2023/index.html
Update content German OWASP Day
> Update content German OWASP Day

- 2023/sponsors/index.html
> Y-Security als Sponsor hinzugefügt

- 2023/index.html
Update CFP announcement and remove Call for Trainings
> Update CFP announcement and remove CFT

- 2023/cfp/index.html
> Erster Schwung PK-Mitglieder

- 2023/sponsors/index.html
> DB Systel Standardsponsor

- 2023/sponsors/index.html
> Added IriusRisk as Sponsor

- 2024/cfp.html
- 2024/css/styles.css
- 2024/en/index.html
- 2024/index.html
- add archive links to GOD2024 page
- add target blank when opening CfP page
> feat: add archive links

- 2024/cfp.html
- 2024/en/cfp.html
- change format list in CfP page
> Style: update list formatting CfP

- 2024/cfp.html
- 2024/en/cfp.html
- justify left of CFP content for better readability
> style: justify left CFP content

- 2024/en/index.html
- 2024/index.html
- include CPE information
- add Eventbrite link to event
> feat: add eventbrite link and CPE info

- 2024/cfp.html
- 2024/en/cfp.html
- 2024/en/index.html
- 2024/index.html
- disable cfp links
- add information cfp is closed
> feat: close cfp

- 2024/css/styles.css
- remove unused CSS code
- adjust header hover color to blue
> chore: adjust header hover color

- 2024/css/styles.css
- 2024/en/index.html
- 2024/index.html
- 2024/program-detail.html
- adjust program detail style sheet
- add trainings and talks to german page
- add trainings and talks to english page
> feat: add program details to english and german page

- 2024/en/index.html
- 2024/index.html
> feat: add language tag to talks

- 2024/en/index.html
- 2024/index.html
- 2024/program-detail.html
- remove and replace Björn K. as speaker
- remove empty speaker slot
> feat: replace speaker

- 2024/en/index.html
- 2024/index.html
- 2024/program-detail.html
Ich habe die ganzen Inhalte CSRF/XS-leaks, COEP, CORP, COOP nicht problemlos in die gegebenen 25 Minuten packen können ohne zu hetzen. Lieber würde ich mir Zeit nehmen und die Konzepte so darlegen, dass man das Framework drumherum verstehen kann.
Das Thema ist im Endeffekt dasselbe, aber ich hab zu viel Namedropping im abstract, als dass ich das so stehen lassen würde. Ich hab z.B. CSRF & COEP rausgenommen um ein besseres Gesamtbild darstellen zu können.
> Update talk title and abstract to better match the content

- 2025/cfp.html
- 2025/en/cfp.html
* Update topics
* Add sections for top submission + reasons for rejection
* Update to PC members (status 2025-06-27)
Open:
* Create conference in Easychair (~Sunday)
* Do we really want to pay the train ticket for Lightning talks?
* Make clear that trainings are not included for speakers
* Make clear this is not a CfT
> Update 2024 --> 2025 for DE, EN

- 2025/cfp.html
- 2025/en/cfp.html
... and rearrange order so that it doesn't appear that the women come last in a row
> Update program committee

- 2025/en/index.html
- 2025/index.html
- add english program
- add german program
> Add programm

- 2025/program-detail.html
Anpassung des Talk Contents, sodass er nur noch den für die Besuchenden relevanten Teil enthält.
Ausserdem Erweiterung der Speaker Beschreibungen, da diese für das CfP Formular stark gekürzt werden mussten.
> Adjust talk content and speaker information
